[tool.poetry]
name = "mancrop"
version = "0.1.0"
description = ""
authors = ["徐铭 <xumingxs@qq.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "download" },
    { include = "error_handler" },
    { include = "log" },
    { include = "modules" },
    { include = "utils" },
]



[tool.poetry.dependencies]
python = "^3.12"
aiofiles = "23.2.1"
aiohttp = "3.9.5"
aioshutil = "1.4"
aiosignal = "1.3.1"
annotated-types = "0.7.0"
ansicon = "1.89.0"
anyio = "4.4.0"
arrow = "1.3.0"
attrs = "23.2.0"
beautifulsoup4 = "4.12.3"
binaryornot = "0.4.4"
blessed = "1.20.0"
brotli = "1.1.0"
bs4 = "0.0.2"
certifi = "2024.7.4"
chardet = "5.2.0"
charset-normalizer = "3.3.2"
click = "8.1.7"
colorama = "0.4.6"
cookiecutter = "2.6.0"
crawlee = "0.1.0"
docutils = "0.21.2"
editor = "1.6.6"
eval-type-backport = "0.2.0"
filelock = "3.15.4"
frozenlist = "1.4.1"
greenlet = "3.0.3"
h11 = "0.14.0"
httpcore = "1.0.5"
httpx = "0.27.0"
idna = "3.7"
inquirer = "3.3.0"
jinja2 = "3.1.4"
jinxed = "1.2.1"
markdown-it-py = "3.0.0"
markupsafe = "2.1.5"
mdurl = "0.1.2"
more-itertools = "10.3.0"
multidict = "6.0.5"
playwright = "1.45.0"
psutil = "6.0.0"
pydantic = "2.8.2"
pydantic-settings = "2.3.4"
pydantic-core = "2.20.1"
pyee = "11.1.0"
pygments = "2.18.0"
python-dateutil = "2.9.0.post0"
python-dotenv = "1.0.1"
python-slugify = "8.0.4"
pyyaml = "6.0.1"
readchar = "4.1.0"
requests = "2.32.3"
requests-file = "2.1.0"
rich = "13.7.1"
runs = "1.2.2"
shellingham = "1.5.4"
six = "1.16.0"
sniffio = "1.3.1"
sortedcollections = "2.1.0"
sortedcontainers = "2.4.0"
soupsieve = "2.5"
text-unidecode = "1.3"
tldextract = "5.1.2"
typer = "0.12.3"
types-python-dateutil = "2.9.0.20240316"
typing-extensions = "4.12.2"
urllib3 = "2.2.2"
wcwidth = "0.2.13"
xmod = "1.8.1"
yarl = "1.9.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
